export const tableHead = [
  'Company Name',
  'Email Address',
  'Phone No',
  'Contact Person',
  'Facilitator',
  'Sites',
  'Tenants',
  'Tenants Groups',
  'Actions',
];

export const clientInfo = [
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
  {
    companyName: 'Infosys',
    email: 'management@infosys.com',
    phoneNo: '+91 9563214587',
    contactPerson: 'Vijayent Roy',
    facilitator: '--',
    sites: '12',
    tenants: '--',
    tenantGroup: '--',
    action: '',
  },
];
